
% =========================================================================
%% Workflow:
% 1. Automated execution of compiled C simulation program (seird_model or
%    seird_model.exe) that generates scenario_*.csv output files
%
% 2. Multi-scenario analysis:
%    - Automatically detects and processes all scenario_*.csv files
%    - Reads corresponding parameters from parameters.csv
%    - Analyzes up to 9 scenarios simultaneously
%
% 3. Comprehensive visualization (5 figures):
%    - Figure 1: 3×3 grid showing S,E,I,R,D dynamics for all scenarios
%    - Figure 2: detailed full-scale view of Scenario 4
%    - Figure 3: effective reproduction number (R_eff) trajectories
%    - Figure 4: bar graph of epidemic timing metrics (decline/end times)
%    - Figure 5: bar graph of population impact metrics (peak infected/deaths)
%
% 4. Quantitative metrics computation:
%    - Peak infected population
%    - Total deaths (final cumulative deceased)
%    - Time to epidemic decline (when Reff drops below 1 permanently)
%    - Time to epidemic end (when E and I fall below 1 permanently)
%
% 5. Summary output:
%    - Console display of all metrics
%    - CSV export (summary_results.csv) for further analysis
%
% Functions:
% - epidemic_end_day(): determines when E and I both drop below 1 permanently
% - epidemic_decline_day(): determines when R_eff drops below 1 permanently
% =========================================================================

%% AUTOMATION: 
% run C simulation, read all scenario_*.csv files,
% plot S, E, I, R, D for each scenario, compute summary metrics.

% clean MATLAB environment
clear; 
clc; 
close all; 

% run the compiled C program
% the C program must generate scenario_1.csv, scenario_2.csv, ... etc.

if ispc
    % if Windows
    % the executable must be: seird_model.exe
    status = system("seird_model.exe");
else
    % if MacOS or Linux
    % the executable must be: seird_model
    status = system("./seird_model");
end

%% Find all CSV files generated by the C simulation
% the '*' wildcard matches any characters (e.g. 1, 2, ..., 9)
files = dir("scenario_*.csv");
num_files = length(files);
parameters = readtable("parameters.csv"); % read parameters CSV into a table

%% Create figures for plotting
figure(1);  
tiledlayout(3, 3);   % 3×3 grid of subplots (for 9 scenarios)

sgtitle('SEIRD Model — All Compartments for All Scenarios');

figure(3);           % creates a figure for Reff plot
hold on; grid on;
colors = hsv(num_files);

%% Prepare a summary table
summary = table('Size', [num_files 5], 'VariableTypes', {'string','double','double','double','double'}, ...
                'VariableNames', {'Scenario','PeakInfected','TotalDeaths','TimeToDecline','TimeToEnd'});

%% Loop through each scenario file
for i = 1:num_files
    
    fname = files(i).name;
    csv = readtable(fname);   % read scenario i CSV into a table

    % Plot S, E, I, R, D all together
    figure(1);  
    nexttile;  % move to next subplot (in the 3×3 grid)
    hold on;
    plot(csv.time, csv.S, 'b','LineWidth', 1.4);  % plot Susceptible (S)
    plot(csv.time, csv.E, 'm', 'LineWidth', 1.4); % plot Exposed     (E)
    plot(csv.time, csv.I, 'r', 'LineWidth', 1.4); % plot Infected    (I)
    plot(csv.time, csv.R, 'g', 'LineWidth', 1.4); % plot Recovered   (R)
    plot(csv.time, csv.D, 'k', 'LineWidth', 1.4); % plot Deceased    (D)
    hold off;

    % show only first 300 days on x-axis to visually center the curves
    xlabel('Time (days)');
    xlim([0 300]); 
    ylabel('Population');
    scenarioName = sprintf('Scenario %d', i);
    title(scenarioName);
    grid on;

    p = parameters(i,:);      % extract scenario i parameters 
    beta  = p.beta;
    gamma = p.gamma;
    mu    = p.mu;
    N     = p.N;

    % Reff: effective reproduction number (average number of secondary 
    % infections caused by one infectious individual)
    Reff = (beta .* csv.S) ./ ((gamma + mu) * N);
    figure(3);
    plot(csv.time, Reff, 'LineWidth', 1.6, 'Color', colors(i,:),'DisplayName', scenarioName);

    % -------- Summary metrics --------
    peakI = max(csv.I);                                      % peak infected
    totalD = csv.D(end);                                     % final deaths
    timeToDecline = epidemic_decline_day(csv.time, Reff);    % epidemic decline time
    timeToEnd = epidemic_end_day(csv.time, csv.E, csv.I);    % epidemic end time

    % store in summary table
    summary.Scenario(i)      = scenarioName;
    summary.PeakInfected(i)  = peakI;
    summary.TotalDeaths(i)   = totalD;
    summary.TimeToDecline(i) = timeToDecline;  % in days
    summary.TimeToEnd(i)     = timeToEnd;      % in days
   
end

% ---- Legend for SEIRD (Figure 1) ----
figure(1);
lgd = legend({'S','E','I','R','D'});
lgd.Layout.Tile = 'north';
lgd.Orientation = 'horizontal';

% ---- Plot of Scenario 4 (Figure 2) ----
% full-scale view of scenario 4 because the epidemic is longer
figure(2); clf;
csv4 = readtable(files(4).name); % consider scenario_4.csv only

hold on;
plot(csv4.time, csv4.S, 'b','LineWidth', 1.6); % plot Susceptible (S)
plot(csv4.time, csv4.E, 'm','LineWidth', 1.6); % plot Exposed     (E)
plot(csv4.time, csv4.I, 'r','LineWidth', 1.6); % plot Infected    (I)
plot(csv4.time, csv4.R, 'g','LineWidth', 1.6); % plot Recovered   (R)
plot(csv4.time, csv4.D, 'k','LineWidth', 1.6); % plot Deceased    (D)
hold off;

title('Scenario 4');        % shows 2000 days on x-axis by default
xlabel('Time (days)');
ylabel('Population');
legend('S','E','I','R','D'); 
grid on;

% ---- Legend and labels for Reff (Figure 3) ----
figure(3);
legend('show','Location','best');
xlim([0 800]); 
xlabel('Time (days)');
ylabel('R_{eff}(t)');
title('R_{eff}(t) for all scenarios');
grid on;


%% Creation of bar graphs for time and population metrics 
% ---- Time metrics (Figure 4) ----
% create a bar graph to show time to decline and time to end of the
% epidemic for each scenario
scenarios = summary.Scenario;  
dataTime = [summary.TimeToDecline, summary.TimeToEnd];
figure(4);
h = bar(dataTime, 'grouped');    % create a bar graph for time metrics

barColors = {'b', 'c'};      
for k = 1:length(h)
    h(k).FaceColor = barColors{k};
end

% set the x-axis tick labels to the values in "scenarios" and place ticks at 1:length(scenarios)
set(gca, 'XTickLabel', scenarios, 'XTick', 1:length(scenarios)); 

ylabel('Days'); 
title('Epidemic Timing Metrics');
legend({'Time To Decline', 'Time To End'}, 'Location', 'northwest');
xtickangle(45); % rotate x-axis tick labels by 45 degrees for readability
grid on;

% ---- Population metrics (Figure 5) ----
% create a bar graph to show the peak infected and total deceased
% individuals for each scenario
dataPop = [summary.PeakInfected, summary.TotalDeaths];
figure(5);
h = bar(dataPop, 'grouped');    % create a bar graph for population metrics

barColors = {'y', 'r'};            
for k = 1:length(h)
    h(k).FaceColor = barColors{k};
end

% set the x-axis tick labels to the values in "scenarios" and place ticks at 1:length(scenarios)
set(gca, 'XTickLabel', scenarios, 'XTick', 1:length(scenarios)); 

ylabel('Population');
title('Epidemic Population Metrics');
legend({'Peak Infected', 'Total Deaths'}, 'Location', 'northwest');
xtickangle(45); % rotate x-axis tick labels by 45 degrees for readability
grid on;

%% Save figures 1 to 5 in as a .png
for i = 1:5
    saveas(figure(i), ['figure_' num2str(i) '.png']);
    disp(['Figure ' num2str(i) ' saved as figure_' num2str(i) '.png'] );
end

%% Show and save summary
disp("Summary of Scenario Outcomes");
disp(summary);

writetable(summary, "summary_results.csv");
fprintf("\nSummary saved as summary_results.csv\n");

%% function: determine epidemic end time
% inputs:
%   time - vector of time points (in days)
%   E    - vector of exposed individuals over time
%   I    - vector of infectious individuals over time
%
% output:
%   t_end - first time when E and I stay permanently below threshold
%           returns 0 if no such time exists

function t_end = epidemic_end_day(time, E, I)
    threshold = 1;

    % logical arrays where E and I are below threshold
    belowE = E < threshold;
    belowI = I < threshold;

    % only times when both are below threshold
    bothBelow = belowE & belowI;

    lastTrueFromK = cumprod(bothBelow, "reverse"); % cumulative product starting from the end
    % lastTrueFromK(i) = 1 if, from i to the end, bothBelow is always true

    % find the first k such that from k to end, all values are true
    idx = find(lastTrueFromK, 1);

    if isempty(idx)
        t_end = 0;
    else
        t_end = time(idx);
    end
end

%% function: determine epidemic decline time
% inputs:
%   time - vector of time points (in days)
%   Reff - vector of effective reproduction number over time
%
% output:
%   t_decline - first time when Reff stays permanently below threshold (1)
%               returns 0 if no such time exists

function t_decline = epidemic_decline_day(time, Reff)
    threshold = 1;    
    n = length(time);

    % scan all time points to find the first day after which Reff
    % stay below threshold 
    for k = 1:n
        if all(Reff(k:end) < threshold)
            t_decline = time(k); % first time after which Reff stays permanently < 1
            return;
        end
    end
    t_decline = 0; 
end
  